version: "3.8"
services:
  client:
    container_name: aqibj_client
    build: ./client
    ports:
      - 3000:3000
    networks:
      - blog

  posts:
    container_name: aqibj_posts
    build: ./posts
    ports:
      - 4000:4000
    networks:
      - blog
  
  comments:
    container_name: aqibj_comments
    build: ./comments
    ports:
      - 4001:4001
    networks:
      - blog
  
  query:
    container_name: aqibj_query
    build: ./query
    ports:
      - 4002:4002
    networks:
      - blog

  moderation:
    container_name: aqibj_moderation
    build: ./moderation
    ports:
      - 4003:4003
    networks:
      - blog

  events:
    container_name: aqibj_events
    build: ./event-bus
    ports:
      - 4005:4005
    networks:
      - blog

networks:
  blog: